--ALTER TABLE Envio DROP CONSTRAINT PK_Envio;

--ALTER TABLE Cliente DROP CONSTRAINT FK_Cliente;

--ALTER TABLE Pedido DROP CONSTRAINT FK_Pedido;

DROP TABLE Cliente;

DROP TABLE Pedido;

DROP TABLE Fabrica;

DROP TABLE Articulo;

DROP TABLE Envio;


--DROP DATABASE MDASDYOBBDD_ARTYENC;

