IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'MDASDYOBBDD_ARTYENC')
BEGIN

CREATE DATABASE MDASDYOBBDD_ARTYENC;
  
CREATE TABLE envio (
	ID_ENVIO INT IDENTITY (1, 1) NOT NULL,
	CALLE VARCHAR(90) NOT NULL,
	COMUNA VARCHAR(90) NOT NULL,
	CIUDAD VARCHAR(45) NOT NULL,
	CONSTRAINT pk1 PRIMARY KEY(ID_ENVIO)
);



CREATE TABLE cliente (
	ID_CLIENTE INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	ID_ENVIO int NOT NULL,
	SALDO INT NOT NULL, --
	LIMITE_CREDITO INT NOT NULL DEFAULT 3000000, --MAXIMO 3.000.000
	DESCUENTO INT NOT NULL,
	CONSTRAINT fk1 FOREIGN KEY(ID_ENVIO)
	REFERENCES envio (ID_ENVIO)
);


CREATE TABLE pedido (
	ID_ENVIO int NOT NULL,
	FECHA DATE NOT NULL DEFAULT GETDATE(),
	CONSTRAINT fk1 FOREIGN KEY(ID_ENVIO)
	REFERENCES envio (ID_ENVIO)
);



CREATE TABLE articulo (
	ID_ARTICULO INT IDENTITY (1, 1) PRIMARY KEY,
	DESCRIPCION VARCHAR (255) NOT NULL,
	);


CREATE TABLE fabrica (
    ID_FABRICA int,
    TELEFONO int

);

END;
GO


