IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'MDASDYOBBDD_ARTYENC')
BEGIN

CREATE DATABASE MDASDYOBBDD_ARTYENC;
  
USE MDASDYOBBDD_ARTYENC;

CREATE TABLE dbo.Envio (
	ID_ENVIO INT IDENTITY (1, 1) NOT NULL,
	CALLE VARCHAR(90) NOT NULL,
	COMUNA VARCHAR(90) NOT NULL,
	CIUDAD VARCHAR(45) NOT NULL,
	CONSTRAINT PK_Envio PRIMARY KEY(ID_ENVIO)
);



CREATE TABLE dbo.Cliente (
	ID_CLIENTE INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	ID_ENVIO int NOT NULL,
	SALDO INT NOT NULL, --
	LIMITE_CREDITO INT NOT NULL DEFAULT 3000000, --MAXIMO 3.000.000
	DESCUENTO INT NOT NULL,
	CONSTRAINT FK_Cliente FOREIGN KEY(ID_ENVIO)
	REFERENCES envio (ID_ENVIO)
);


CREATE TABLE dbo.Pedido (
	ID_ENVIO int NOT NULL,
	FECHA DATE NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Pedido FOREIGN KEY(ID_ENVIO)
	REFERENCES envio (ID_ENVIO)
);



CREATE TABLE dbo.Articulo (
	ID_ARTICULO INT IDENTITY (1, 1) PRIMARY KEY,
	DESCRIPCION VARCHAR (255) NOT NULL,
	);


CREATE TABLE dbo.Fabrica (
    ID_FABRICA int,
    TELEFONO int

);

END;
GO


