USE MDASDYOBBDD_ARTYENC;

SET IDENTITY_INSERT dbo.Envio ON
SET IDENTITY_INSERT dbo.Cliente ON
--SET IDENTITY_INSERT dbo.Pedido ON
SET IDENTITY_INSERT dbo.Articulo ON
--SET IDENTITY_INSERT dbo.Fabrica ON

INSERT INTO dbo.Envio (ID_ENVIO,CALLE,COMUNA,CIUDAD) VALUES (1,'Carrer Francesc Ferrer i Guardia','Can Borell','Mollet del Valles');
INSERT INTO dbo.Cliente (ID_ENVIO,SALDO,LIMITE_CREDITO,DESCUENTO) VALUES (1,120,200,5);
INSERT INTO dbo.Pedido (ID_ENVIO,FECHA) VALUES (1,'2004-01-22');
INSERT INTO dbo.Articulo (ID_ARTICULO,DESCRIPCION) VALUES (1,'Llave inglesa Bosch');
INSERT INTO dbo.Fabrica (TELEFONO) VALUES ('605228581');


SET IDENTITY_INSERT dbo.Envio OFF
SET IDENTITY_INSERT dbo.Cliente OFF
--SET IDENTITY_INSERT dbo.Pedido OFF
SET IDENTITY_INSERT dbo.Articulo OFF
--SET IDENTITY_INSERT dbo.Fabrica OFF


GO
