USE MDASDYOBBDD_ARTYENC;

SET IDENTITY_INSERT envio ON

INSERT INTO envio (ID_ENVIO,CALLE,COMUNA,CIUDAD) VALUES (1,'Carrer Francesc Ferrer i Guardia','Can Borell','Mollet del Valles');

SET IDENTITY_INSERT envio OFF
GO

SET IDENTITY_INSERT cliente ON

INSERT INTO cliente (ID_CLIENTE,ID_ENVIO,SALDO,LIMITE_CREDITO,DESCUENTO) VALUES (1,1,120,200,5);


SET IDENTITY_INSERT cliente OFF
GO


SET IDENTITY_INSERT pedido ON

INSERT INTO pedido (ID_ENVIO,FECHA) VALUES (1,'2004-01-22');


SET IDENTITY_INSERT pedido OFF
GO